version: '3.8'

services:
  Front-End:
    image: ghcr.io/tup-utn-frc-lciii/flight-check-in-front-end
    ports:
      - "4200:4200"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      app-net:
    environment:
      API_URL: http://localhost:8080/ #Ignorar

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      app-net:
    depends_on:
      - back-end
      - Front-End


  back-end:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      app-net:
      back-end-net:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vuelos
      SPRING_DATASOURCE_USERNAME: utn
      SPRING_DATASOURCE_PASSWORD: utn

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: vuelos
      MYSQL_USER: utn
      MYSQL_PASSWORD: utn
      MYSQL_ROOT_PASSWORD: utn
      TZ: America/Argentina/Buenos_Aires #Zona horaria
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      back-end-net:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  app-net:
  back-end-net: